CREATE TABLE [dbo].[Note]
(
	[NoteId] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] NVARCHAR(128) NOT NULL,
    [Note] VARCHAR(5000) NOT NULL,
	CONSTRAINT [FK_Note_User] FOREIGN KEY ([UserId]) REFERENCES [User]([UserId])
)
